export const THEME_STORAGE_KEY = "gold-title-colorway";

const classicVars = {
  "--color-paper": "#f8f6f0",
  "--color-paper-2": "#ebe6dc",
  "--color-paper-3": "#ddd4c4",
  "--color-ink": "#171717",
  "--color-ink-2": "#252525",
  "--color-ink-3": "#343434",
  "--color-bone": "#fffdf7",
  "--color-charcoal": "#1f2326",
  "--color-charcoal-2": "#3f474d",
  "--color-blood": "#a43d35",
  "--color-blood-deep": "#7d2d28",
  "--color-gold": "#9b7a32",
  "--color-gold-bright": "#b99343",
  "--color-gold-deep": "#6e5727",
};

export const THEME_PRESETS = [
  {
    id: "classic",
    name: "Jetzt",
    description: "Die aktuelle helle Gold-Title-Palette.",
    colors: ["#f8f6f0", "#1f2326", "#9b7a32", "#a43d35"],
    vars: classicVars,
  },
  {
    id: "darker",
    name: "Dunkler",
    description: "Etwas schwerer, weniger Creme, mehr Nachtclub.",
    colors: ["#e5ded1", "#17191c", "#846424", "#8f2f2c"],
    vars: {
      ...classicVars,
      "--color-paper": "#e5ded1",
      "--color-paper-2": "#d1c5b3",
      "--color-paper-3": "#b8a98f",
      "--color-ink": "#111214",
      "--color-ink-2": "#1b1d20",
      "--color-ink-3": "#272a2e",
      "--color-bone": "#fff9ec",
      "--color-charcoal": "#17191c",
      "--color-charcoal-2": "#2d3338",
      "--color-blood": "#8f2f2c",
      "--color-blood-deep": "#67211f",
      "--color-gold": "#846424",
      "--color-gold-bright": "#a98233",
      "--color-gold-deep": "#5b451d",
    },
  },
  {
    id: "gore",
    name: "Gore",
    description: "Schwarzrote Fight-Night-Optik mit aggressivem Rot.",
    colors: ["#160b0b", "#f6eadb", "#d92323", "#85000c"],
    vars: {
      ...classicVars,
      "--color-paper": "#160b0b",
      "--color-paper-2": "#211111",
      "--color-paper-3": "#321416",
      "--color-ink": "#070303",
      "--color-ink-2": "#100707",
      "--color-ink-3": "#1d0b0d",
      "--color-bone": "#f6eadb",
      "--color-charcoal": "#f6eadb",
      "--color-charcoal-2": "#d3b8a4",
      "--color-blood": "#d11124",
      "--color-blood-deep": "#85000c",
      "--color-gold": "#d92323",
      "--color-gold-bright": "#ff4d3d",
      "--color-gold-deep": "#99141c",
    },
  },
  {
    id: "gromda",
    name: "Gromda",
    description: "Sehr dunkel, hartes Rot, graue Kontraste.",
    colors: ["#050505", "#dddddd", "#cc0027", "#8a001a"],
    vars: {
      ...classicVars,
      "--color-paper": "#050505",
      "--color-paper-2": "#111111",
      "--color-paper-3": "#202020",
      "--color-ink": "#000000",
      "--color-ink-2": "#0a0a0a",
      "--color-ink-3": "#151515",
      "--color-bone": "#dddddd",
      "--color-charcoal": "#dddddd",
      "--color-charcoal-2": "#a8a8a8",
      "--color-blood": "#cc0027",
      "--color-blood-deep": "#8a001a",
      "--color-gold": "#cc0027",
      "--color-gold-bright": "#ff244d",
      "--color-gold-deep": "#99001d",
    },
  },
  {
    id: "noir",
    name: "Noir Gold",
    description: "Premium-Nachtlook mit warmem Gold und tiefem Schwarz.",
    colors: ["#0b0b0a", "#f3ead8", "#c89b3c", "#9f1f26"],
    vars: {
      ...classicVars,
      "--color-paper": "#0b0b0a",
      "--color-paper-2": "#151411",
      "--color-paper-3": "#242016",
      "--color-ink": "#030303",
      "--color-ink-2": "#090908",
      "--color-ink-3": "#171612",
      "--color-bone": "#f3ead8",
      "--color-charcoal": "#f3ead8",
      "--color-charcoal-2": "#c7b89b",
      "--color-blood": "#9f1f26",
      "--color-blood-deep": "#671318",
      "--color-gold": "#c89b3c",
      "--color-gold-bright": "#f0c66a",
      "--color-gold-deep": "#806120",
    },
  },
  {
    id: "ice",
    name: "Ice",
    description: "Kühl, hell und sauber mit blauem Stahl-Kontrast.",
    colors: ["#eef3f7", "#18232d", "#4d8fb3", "#b22a35"],
    vars: {
      ...classicVars,
      "--color-paper": "#eef3f7",
      "--color-paper-2": "#d8e3ea",
      "--color-paper-3": "#bdccd6",
      "--color-ink": "#101820",
      "--color-ink-2": "#18232d",
      "--color-ink-3": "#253445",
      "--color-bone": "#fbfdff",
      "--color-charcoal": "#18232d",
      "--color-charcoal-2": "#3a5265",
      "--color-blood": "#b22a35",
      "--color-blood-deep": "#7f1c25",
      "--color-gold": "#4d8fb3",
      "--color-gold-bright": "#7dbbda",
      "--color-gold-deep": "#2c5f7c",
    },
  },
  {
    id: "neon",
    name: "Neon",
    description: "Schwarz, Cyan, Magenta und grelle Fight-Night-Energie.",
    colors: ["#05070b", "#e9fbff", "#00d5ff", "#ff214f"],
    vars: {
      ...classicVars,
      "--color-paper": "#05070b",
      "--color-paper-2": "#0b1118",
      "--color-paper-3": "#121d27",
      "--color-ink": "#020306",
      "--color-ink-2": "#070a10",
      "--color-ink-3": "#101824",
      "--color-bone": "#e9fbff",
      "--color-charcoal": "#e9fbff",
      "--color-charcoal-2": "#8ec5d4",
      "--color-blood": "#ff214f",
      "--color-blood-deep": "#a9002d",
      "--color-gold": "#00d5ff",
      "--color-gold-bright": "#69ecff",
      "--color-gold-deep": "#0085aa",
    },
  },
  {
    id: "royal",
    name: "Royal",
    description: "Dunkles Blau mit Champagner-Gold und Rot-Akzent.",
    colors: ["#08111f", "#eef1f5", "#d6ad54", "#b4333a"],
    vars: {
      ...classicVars,
      "--color-paper": "#08111f",
      "--color-paper-2": "#101d31",
      "--color-paper-3": "#1a2b47",
      "--color-ink": "#030812",
      "--color-ink-2": "#08101d",
      "--color-ink-3": "#13213a",
      "--color-bone": "#eef1f5",
      "--color-charcoal": "#eef1f5",
      "--color-charcoal-2": "#aeb8c7",
      "--color-blood": "#b4333a",
      "--color-blood-deep": "#762027",
      "--color-gold": "#d6ad54",
      "--color-gold-bright": "#f1d384",
      "--color-gold-deep": "#8b6c2d",
    },
  },
  {
    id: "toxic",
    name: "Toxic",
    description: "Schwarzgrün, giftiger Akzent, sehr plakativ.",
    colors: ["#07110b", "#edf8df", "#96d92f", "#c42032"],
    vars: {
      ...classicVars,
      "--color-paper": "#07110b",
      "--color-paper-2": "#0e1d12",
      "--color-paper-3": "#18301c",
      "--color-ink": "#020704",
      "--color-ink-2": "#061009",
      "--color-ink-3": "#102017",
      "--color-bone": "#edf8df",
      "--color-charcoal": "#edf8df",
      "--color-charcoal-2": "#b7c99b",
      "--color-blood": "#c42032",
      "--color-blood-deep": "#81111f",
      "--color-gold": "#96d92f",
      "--color-gold-bright": "#c6ff61",
      "--color-gold-deep": "#5f8f17",
    },
  },
  {
    id: "vintage",
    name: "Vintage",
    description: "Altes Fight-Poster: Papier, Tinte, Messing und Rostrot.",
    colors: ["#efe0bf", "#241d18", "#8b6828", "#9b3028"],
    vars: {
      ...classicVars,
      "--color-paper": "#efe0bf",
      "--color-paper-2": "#dbc79e",
      "--color-paper-3": "#c2a876",
      "--color-ink": "#18110d",
      "--color-ink-2": "#241d18",
      "--color-ink-3": "#342820",
      "--color-bone": "#fff1d1",
      "--color-charcoal": "#241d18",
      "--color-charcoal-2": "#5f4935",
      "--color-blood": "#9b3028",
      "--color-blood-deep": "#68201b",
      "--color-gold": "#8b6828",
      "--color-gold-bright": "#b78935",
      "--color-gold-deep": "#5a421b",
    },
  },
] as const;

export type ThemePresetId = (typeof THEME_PRESETS)[number]["id"];

export function isThemePresetId(value: string | null): value is ThemePresetId {
  return THEME_PRESETS.some((preset) => preset.id === value);
}

export function applyThemePreset(theme: ThemePresetId, root: HTMLElement = document.documentElement) {
  const preset = THEME_PRESETS.find((item) => item.id === theme) ?? THEME_PRESETS[0];

  root.dataset.colorway = preset.id;
  Object.entries(preset.vars).forEach(([name, value]) => {
    root.style.setProperty(name, value);
  });
}
